services:
  - type: web
    runtime: python
    name: Flask-Healthcare-Application
    repo: https://github.com/Dannieib/Flask-Healthcare-Application--NXU
    numInstances: 1
    region: frankfurt
    plan: starter
    branch: main
    buildCommand: pip install  -r Src/requirements.txt
    preDeployCommand: python migrate.py
    startCommand: gunicorn -w 4 -b 0.0.0.0:5000 app:app
    autoDeploy: false
    maxShutdownDelaySeconds: 300
