services:
  - type: web
    runtime: python
    name: Flask-Healthcare-Application
    repo: https://github.com/Dannieib/Flask-Healthcare-Application--NXU
    numInstances: 1
    region: frankfurt
    plan: starter
    branch: main
    envVars:
      - key: PYTHONPATH
        value: "/opt/render/project/Src"
    buildCommand: pip install -r Src/requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:5000 Src.app:app
    autoDeploy: false
    maxShutdownDelaySeconds: 300
